resolver: lts-19.6
packages:
- sydtest
- sydtest-aeson
- sydtest-amqp
- sydtest-autodocodec
- sydtest-discover
- sydtest-hedgehog
- sydtest-hedis
- sydtest-hspec
- sydtest-mongo
- sydtest-persistent
- sydtest-persistent-postgresql
- sydtest-persistent-sqlite
- sydtest-process
- sydtest-rabbitmq
- sydtest-servant
- sydtest-typed-process
- sydtest-wai
- sydtest-webdriver
- sydtest-webdriver-screenshot
- sydtest-webdriver-yesod
- sydtest-yesod

- sydtest-misbehaved-test-suite

extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

- github: NorfairKing/safe-coloured-text
  commit: 675cb01fce5f46718416d7746de5b856ed90a63f
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/autodocodec
  commit: c8c6965d97a04fb483c03c0a8479533f252a34d7
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

- github: NorfairKing/validity
  commit: 657cf4bdc2731387abea6e707b88d381d5218616
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-case-insensitive
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector

- github: georgefst/hs-webdriver
  commit: cf9c387de7c1525ffbcd58125ccb3f798a97a2bb

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages -O0


nix:
  shell-file: shell.nix
