# Track the stackage nightly version used in the nixpkgs commit we use
# https://github.com/NixOS/nixpkgs/blob/4e0d3868c679da20108db402785f924daa1a7fb5/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L80
resolver: lts-16.20
allow-newer: false
packages:
- sydtest
- sydtest-amqp
- sydtest-discover
- sydtest-hedis
- sydtest-mongo
- sydtest-persistent-postgresql
- sydtest-persistent-sqlite
- sydtest-process
- sydtest-rabbitmq
- sydtest-servant
- sydtest-typed-process
- sydtest-wai
- sydtest-yesod
- sydtest-aeson
extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842
- github: NorfairKing/yamlparse-applicative
  commit: 9059edbd30c7d3b07cd97306158c4f2f33bb7a44
  subdirs:
    - yamlparse-applicative
- github: NorfairKing/safe-coloured-text
  commit: 3fe46e3102a02987ebb8ee389c15a9c57df21ccc
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef


nix:
  shell-file: shell.nix
