name: sydtest-hedis
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"
category: Testing
synopsis: An hedis companion library for sydtest

extra-source-files:
- LICENSE.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - hedis
  - network
  - path
  - path-io
  - port-utils
  - sydtest
  - sydtest-typed-process
  - text
  - typed-process

tests:
  sydtest-hedis-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hedis
    - sydtest
    - sydtest-hedis
    when:
      - condition: flag(sydtest_integration_tests)
        then:
          buildable: True
        else:
          buildable: False

flags:
  sydtest_integration_tests:
    description: Whether to allow building integration tests
    manual: false
    default: true
