name: sydtest-aeson
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"
category: Testing
synopsis: An aeson companion library for sydtest


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - path
  - path-io
  - sydtest

tests:
  sydtest-aeson-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aeson
    - sydtest
    - sydtest-aeson
    - text
    when:
      - condition: flag(sydtest_integration_tests)
        then:
          buildable: True
        else:
          buildable: False

flags:
  sydtest_integration_tests:
    description: Whether to allow building integration tests
    manual: false
    default: true
