name: sydtest-yesod
version: 0.2.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020 Tom Sydney Kerckhove"
category: Testing
synopsis: A yesod companion library for sydtest

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - blaze-builder
    - bytestring
    - case-insensitive
    - containers
    - cookie
    - exceptions
    - http-client
    - http-types
    - mtl
    - network
    - pretty-show
    - sydtest >=0.3
    - sydtest-wai
    - text
    - time
    - wai
    - xml-conduit
    - yesod-core
    - yesod-test

tests:
  sydtest-yesod-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - conduit
    - cookie
    - http-types
    - resourcet
    - sydtest
    - sydtest-yesod
    - text
    - yesod
    - yesod-form

  sydtest-yesod-blog-example-test:
    main: Spec.hs
    source-dirs: blog-example
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - http-client
    - monad-logger
    - mtl
    - persistent
    - persistent-sqlite
    - persistent-template
    - sydtest
    - sydtest-persistent-sqlite
    - sydtest-yesod
    - text
    - yesod
    - yesod-form
