name: sydtest-amqp
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2021 Tom Sydney Kerckhove"
category: Testing
synopsis: An amqp companion library for sydtest


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - amqp
  - async
  - path
  - path-io
  - process
  - sydtest

tests:
  sydtest-amqp-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - sydtest
    - sydtest-amqp
