name: sydtest-persistent
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"
category: Testing
synopsis: A persistent companion library for sydtest


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - monad-logger
  - mtl
  - persistent
  - persistent-template
  - sydtest

tests:
  sydtest-persistent-sqlite-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-logger
    - persistent
    - persistent-sqlite
    - persistent-template
    - sydtest
    - sydtest-persistent
