name: sydtest-typed-process
version: 0.0.0.0
github: "NorfairKing/sydtest"
license: OtherLicense
license-file: LICENSE.md
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2021 Tom Sydney Kerckhove"
category: Testing
synopsis: A typed-process companion library for sydtest

extra-source-files:
- LICENSE.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - sydtest
  - typed-process

tests:
  sydtest-typed-process-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bytestring
    - sydtest
    - sydtest-typed-process
    - typed-process
