name:                sydtest
version:             0.0.0.0
github:              "NorfairKing/sydtest"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - Diff
    - MonadRandom
    - QuickCheck
    - async
    - bytestring
    - containers
    - dlist
    - envparse
    - mtl
    - optparse-applicative
    - path
    - path-io
    - pretty-show
    - quickcheck-io
    - rainbow
    - random-shuffle
    - safe
    - split
    - text
    - yaml
    - yamlparse-applicative

tests:
  sydtest-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - path
    - path-io
    - rainbow
    - stm
    - sydtest

  sydtest-output-test:
    main: Spec.hs
    source-dirs: output-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - path
    - path-io
    - rainbow
    - sydtest
