name: "Nix Build"
on:
  pull_request:
  push:
    branches:
      - development
      - master

jobs:
  hooks:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: cachix/install-nix-action@v14.1
    - uses: cachix/cachix-action@v10
      with:
        name: sydtest
        extraPullNames: yamlparse
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build ci.nix -A pre-commit-check

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        lts:
          - release

    name: CI Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: cachix/install-nix-action@v14.1
    - uses: cachix/cachix-action@v10
      with:
        name: sydtest
        extraPullNames: yamlparse
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build ci.nix -A ${{ matrix.lts }}

